apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: demo-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: demo-app-image
  policy:
    semver:
      range: ^0.0