apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- canary.yaml
- deployment.yaml
- hpa.yaml
images:
  - name: stevenfraser/ci-demo-application
    newName: stevenfraser/ci-demo-application
    newTag: 0.0.1
