---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 3000
  selector:
    app: frontend